import React, { Component } from 'react';
import { Fieldset } from 'primereact/fieldset';
import { Button } from 'primereact/button';

import Stars from './Stars';
import '../css/Stars.css';

console.log("called FAQ");

class FAQ extends Component {

    render() {

        return (
            <div className="faqSection" id="faq" >

                <div class="faq-header">Frequently Asked Questions</div>

                <div class="faq-content">
                    <div class="faq-question">
                        <input id="q1" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q1" class="panel-title">What is The ORB?</label>
                        <div class="panel-content">The ORB is an intense money game with explosive APY farm rates. <br />
                        Players buy ORB, stake ORB, harvest ORB. <br />
                        ORB Staked is locked up for 3 days.<br />
                        When it's unlocked players can sell the generated ORB.</div>
                    </div>

                    <Stars />

                    <div class="faq-question">
                        <input id="q2" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q2" class="panel-title">What are the basic tokenomics?</label>
                        <div class="panel-content">There is a starting supply of 1,000,000 ORB. <br />
                        ORB is generated by staking.<br />
                        1 ORB is required for staking.</div>
                    </div>

                    <div class="faq-question">
                        <input id="q3" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q3" class="panel-title">What is the Contract Address? Where can I buy?</label>
                        <div class="panel-content">CHANGEIT - Addrss here</div>
                    </div>

                    <div class="faq-question">
                        <input id="q4" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q4" class="panel-title">How risky is this?</label>
                        <div class="panel-content">High Risk High Reward - Do not risk more than you can afford to lose.
                        The Liquidity supplied to PancakeSwap cannot be interacted with by the Team.</div>
                    </div>

                    <div class="faq-question">
                        <input id="q5" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q5" class="panel-title">What is the APY?</label>
                        <div class="panel-content">APY 1,000,000% 1 Million APY</div>
                    </div>

                    <Stars />

                    <div class="faq-question">
                        <input id="q6" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q6" class="panel-title">How long is the lock up?</label>
                        <div class="panel-content">3 Days, at the end you can unstake your ORB and claim generated ORB in 1 transaction.</div>
                    </div>

                    <div class="faq-question">
                        <input id="q7" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q7" class="panel-title">Has this been audited?</label>
                        <div class="panel-content">The Self-Audit is here. CHANGEIT</div>
                    </div>


                    <div class="faq-question">
                        <input id="q8" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q8" class="panel-title">Are you related to the previous ORB projects?</label>
                        <div class="panel-content">
                            The team has no relation to the previous ORB projects. <br />
                            This project does not have bugs as the previous one did.
                        </div>
                    </div>

                    <div class="faq-question">
                        <input id="q9" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q9" class="panel-title">How do I play? - Presale</label>
                        <div class="panel-content">Before ORB Staking is enabled and before PancakeSwap Liquidity is provided there will be a public presale.<br />
                        1 BNB = 100 ORB. 1 ORB is required to stake.<br />
                        The BNB generated from this presale will go to PancakeSwap Liquidity.<br />
                        After the presale ends, The ORB Team will call a function in the contract to add Liquidity to PancakeSwap.<br /></div>
                    </div>

                    <Stars />

                    <div class="faq-question">
                        <input id="q10" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q10" class="panel-title">How do I play? - Staking</label>
                        <div class="panel-content">After Liquidity is provided, Staking will be enabled and announced on CHANGEIT-DATE to ensure a fair game.<br />
                        After staking at least 1 ORB, ORB is generated at 1,000,000% APY. <br />
                        The lock up duration is for 3 days. <br />
                        After 3 days of lock up, harvesting is unlocked and players can harvest ORB generated and unstake.<br />
                        ORB can then be sold into PancakeSwap for BNB. <br />
                        Players can only stake once.</div>
                    </div>

                    <div class="faq-question">
                        <input id="q11" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q11" class="panel-title">How do I play? - Ending</label>
                        <div class="panel-content">5 days after the launch of staking, all staking will be disabled and harvest will be unlocked.<br />
                        Players still staking can unstake and harvest generated ORB.<br />
                        The fastest stakers and the fastest harvesters win.</div>
                    </div>

                    <Stars />

                    <div class="faq-question">
                        <input id="q12" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q12" class="panel-title">How do I play? - Awards</label>
                        <div class="panel-content">At the end of 7 days, awards for this money game will be given out.<br />
                        The Player who generates the most BNB from this money game will be awarded an ORB NFT with Professional Art. <br />
                        The Player who generates the most ORB will be awarded 10 BNB.<br />
                        The Player who was first to Stake ORB will earn 1 BNB.<br />
                        The Player who was first to Harvest ORB will earn 1 BNB.<br />
                        Claimers of Awards must be in Telegram or Discord to receive it from The ORB team.<br />
                        After the awards are distributed the game is considered ended and support will no longer be provided.<br /></div>
                    </div>

                    <div class="faq-question">
                        <input id="q13" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q13" class="panel-title"></label>
                        <div class="panel-content"></div>
                    </div>
                </div>

                <Stars />




            </div>
        );
    }
}

export default FAQ;