import React, { Component } from 'react';
import '../css/FAQ.css';
// import { Fieldset } from 'primereact/fieldset';
// import { Button } from 'primereact/button';

// import Stars from './Stars';






console.log("called FAQ");

class FAQ extends Component {
    constructor(props) {
        super(props);

        this.state = {
            contractAddress: '0x23103FE58009cE4F6870245b84031f4A56523b3f',       // CHANGEIT - Change the Address
            selfAuditLink: 'https://www.youtube.com/watch?v=VXhgu2YtZko'  
        };
    }

    render() {

        return (
            <div className="faqSection" id="faq" >

                <div class="disclaimerHeader">
                    DISCLAIMER
                </div>

                <div class="disclaimerContent">
                    THE ORB IS AN EXPERIMENTAL GAME THAT WILL EVOLVE OVER TIME.
                    <br />THE GAME CARRIES A HUGE POTENTIAL FOR REWARDS WITH AN EQUAL AMOUNT OF RISK.
                    <br />PLEASE INVEST WISELY AND NEVER MORE THAN YOU CAN AFFORD TO LOSE.
                    <br />THE TEAM HAS NO RELATION TO THE PREVIOUS ORB PROJECTS.
                    <br />THE SELF-AUDIT IS POSTED ON YOUTUBE FOR ALL TO WATCH.
                </div>

                <a href="https://www.youtube.com/watch?v=q0UXURCY-ZY" class="faq-overview" target="_blank" rel="noopener noreferrer">Watch the Overview on Youtube!</a>

                <div class="faq-header">Frequently Asked Questions</div>

                <div class="faq-content">
                    <div class="faq-question">
                        <input id="q1" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q1" class="panel-title">What is The ORB?</label>
                        <div class="panel-content">
                            The ORB is an experimental crypto game that will continue to be developed over time.
                            <br />The uniqueness of the game is its explosive APY farm rates and the rules that govern them.
                            <br />It enables players to gain large returns on their initial investments.
                            <br />The project will be continually developed over time.
                            <br />The generated liquidity is supplied to PancakeSwap and cannot be interacted with by the Team.
                            <br />The game will last for 7 days only, plan accordingly.
                        </div>
                    </div>

                    {/* <Stars /> */}

                    <div class="faq-question">
                        <input id="q4" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q4" class="panel-title">How to Play?</label>
                        <div class="panel-content">
                            Players buy ORB, stake ORB, harvest ORB.
                            <br /> Staked ORB is locked up for 3 days.
                            <br /> After 3 days, generated ORBs are unlocked and can be sold.
                            <br /> After unlocking players can unstake their ORB and claim the generated ORB in 1 transaction.
                            <br /> Sell the generated ORB to PancakeSwap for huge gains!

                        </div>
                    </div>



                    <div class="faq-question">
                        <input id="q2" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q2" class="panel-title">What are the Basic Tokenomics?</label>
                        <div class="panel-content">
                            The starting supply is 1,000,000 ORB.
                            <br />ORBs are generated by staking.
                            <br />1 ORB is required for staking.
                            <br />The staking reward: APY 1,000,000%
                        </div>
                    </div>


                    <div class="faq-question">
                        <input id="q9" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q9" class="panel-title">How does the Game End?</label>
                        <div class="panel-content">
                            After the 5th day from when staking is enabled, all staking will be disabled and all harvesting will be unlocked.
                            <br />Players still staking can unstake and harvest generated ORBs.
                        </div>
                    </div>


                    <div class="faq-question">
                        <input id="q10" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q10" class="panel-title">How do I win?</label>
                        <div class="panel-content">
                            Be the fastest staker and harvester.
                        </div>
                    </div>

                    {/* <Stars /> */}


                    <div class="faq-question">
                        <input id="q12" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q12" class="panel-title">What are the Rewards?</label>
                        <div class="panel-content">

                            At the end of the 7th day, the game is officially over.
                            <br />The rewards for the game, ORB will be given out:
                            <br />The Player who generated the most BNB will be awarded an official ORB NFT - created by a Professional Artist.
                            <br />The Player who generates the most ORB will be awarded some BNB.
                            <br />The Player who was first to Stake ORB will earn some BNB.
                            <br />The Player who was first to Harvest ORB will earn some BNB.
                            <br />In order to claim any rewards from the ORB team, the player must be a member of one of the official ORB Telegram or Discord communities.
                            <br />After all the awards have been distributed the game round is officially over and support will no longer be provided.
                            <br />Please stay in touch so you don’t miss any news or future game rounds.


                        </div>
                    </div>


                    <div class="faq-question">
                        <input id="q50" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q50" class="panel-title">Will there be more Game Rounds?</label>
                        <div class="panel-content">
                        Yes. 
                        This is revision 1. 
                        <br />There will be improvements as the project grows.
                        </div>
                    </div>




                    <div class="faq-question">
                        <input id="q3" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q3" class="panel-title">What is the Contract Address? Where can I buy?</label>
                        <div class="panel-content">
                            Address: {this.state.contractAddress}
                            <br /> Buy on Pancakeswap or PreSale!
                            <br /> Click the Buy Button on the Menu
                        </div>
                    </div>

                    <div class="faq-question">
                        <input id="q11" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q11" class="panel-title">Presale?</label>
                        <div class="panel-content">
                            PreSale Starts when Contract is Live.
                            <br />1 BNB = 1000 ORB
                            <br />1 ORB is required to stake.
                            <br />Minimum buy of 10 ORB in the Presale.
                            <br />The BNB generated from this presale will go to PancakeSwap Liquidity.
                            <br />After  the  presale  ends, The  ORB  Team  will  call  a  function  in  the  contract  to  add  Liquidity  to PancakeSwap.
                            <br />The ORB team does not control this liquidity.
                        </div>
                    </div>



                    <div class="faq-question">
                        <input id="q5" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q5" class="panel-title">What is the APY?</label>
                        <div class="panel-content">APY 1,000,000% - 1 Million APY</div>
                    </div>

                    {/* <Stars /> */}

                    <div class="faq-question">
                        <input id="q6" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q6" class="panel-title">How long is the Lock Up?</label>
                        <div class="panel-content">3 Days. After unlocking you claim generated ORB as you Unstake.</div>
                    </div>

                    <div class="faq-question">
                        <input id="q7" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q7" class="panel-title">Has this been audited?</label>
                        <div class="panel-content">
                            Self-Audit: {this.state.selfAuditLink}
                        </div>
                    </div>


                    <div class="faq-question">
                        <input id="q8" type="checkbox" class="panel" />
                        <div class="plus">+</div>
                        <label for="q8" class="panel-title">Are you related to the previous ORB projects?</label>
                        <div class="panel-content">
                            The team has no relation to the previous ORB projects.
                        </div>
                    </div>

                    {/* <Stars /> */}



                </div>

                {/* <Stars /> */}




            </div>
        );
    }
}

export default FAQ;