import React, { Component } from 'react';
import { Fieldset } from 'primereact/fieldset';
import { Button } from 'primereact/button';

console.log("called FAQ");

class FAQ extends Component {

    render() {

        return (
            <div className="faqSection" id="faq" >

                <Button className="p-button-raised p-button-rounded p-button-lg"
                    icon="pi pi-question-circle"
                    style={{ fontWeight: 'bold' }}
                    label="FAQ - Frequently Asked Questions" />

                <div className="spacerForFAQsections"></div>


                <Fieldset legend="What is The ORB?">
                    <p>The ORB is an intense money game with explosive APY farm rates. <br />
                        Players buy ORB, stake ORB, harvest ORB. <br />
                        ORB Staked is locked up for 3 days.<br />
                        When it's unlocked players can sell the generated ORB.</p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>



                <Fieldset legend="What are the basic tokenomics?">
                    <p>There is a starting supply of 1,000,000 ORB. <br />
                        ORB is generated by staking.<br />
                        1 ORB is required for staking.


                    </p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="What is the Contract Address? Where can I buy?">
                    <p>CHANGEIT - Addrss here</p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="How risky is this?">
                    <p>High Risk High Reward - Do not risk more than you can afford to lose.
                        The Liquidity supplied to PancakeSwap cannot be interacted with by the Team.


                    </p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="What is the APY?">
                    <p>APY 1,000,000% 1 Million APY </p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="How long is the lock up?">
                    <p>3 Days, at the end you can unstake your ORB and claim generated ORB in 1 transaction.</p>
                </Fieldset>


                <div className="spacerForFAQsections"></div>

                <Fieldset legend="Has this been audited?">
                    <p>The Self-Audit is here. CHANGEIT</p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="Are you related to the previous ORB projects?">
                    <p>The team has no relation to the previous ORB projects. <br />
                        This project does not have bugs as the previous one did. </p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>

                <Fieldset legend="How do I play? - Presale">

                    <p>
                        Before ORB Staking is enabled and before PancakeSwap Liquidity is provided there will be a public presale.<br />
                        1 BNB = 100 ORB. 1 ORB is required to stake.<br />
                        The BNB generated from this presale will go to PancakeSwap Liquidity.<br />
                        After the presale ends, The ORB Team will call a function in the contract to add Liquidity to PancakeSwap.<br />



                    </p>
                </Fieldset>

                <div className="spacerForFAQsections"></div>


                <Fieldset legend="How do I play? - Staking">

                    <p>

                        After Liquidity is provided, Staking will be enabled and announced on CHANGEIT-DATE to ensure a fair game.<br />
                        After staking at least 1 ORB, ORB is generated at 1,000,000% APY. <br />
                        The lock up duration is for 3 days. <br />
                        After 3 days of lock up, harvesting is unlocked and players can harvest ORB generated and unstake.<br />
                        ORB can then be sold into PancakeSwap for BNB. <br />
                        Players can only stake once. 
                        


                    </p>
                </Fieldset>


                <div className="spacerForFAQsections"></div>


                <Fieldset legend="How do I play? - Ending">

                    <p>
                        5 days after the launch of staking, all staking will be disabled and harvest will be unlocked.<br />
                        Players still staking can unstake and harvest generated ORB.<br />
                        The fastest stakers and the fastest harvesters win.


                    </p>
                </Fieldset>


                <div className="spacerForFAQsections"></div>


                <Fieldset legend="How do I play? - Awards">

                    <p>
                        At the end of 7 days, awards for this money game will be given out.<br />
                        The Player who generates the most BNB from this money game will be awarded an ORB NFT with Professional Art. <br />
                        The Player who generates the most ORB will be awarded 10 BNB.<br />
                        The Player who was first to Stake ORB will earn 1 BNB.<br />
                        The Player who was first to Harvest ORB will earn 1 BNB.<br />
                        Claimers of Awards must be in Telegram or Discord to receive it from The ORB team.<br />
                        After the awards are distributed the game is considered ended and support will no longer be provided.<br />


                    </p>
                </Fieldset>




            </div>
        );
    }
}

export default FAQ;